apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: https://eu-central-1-1.aws.cloud2.influxdata.com
    jsonData:
      version: Flux
      organization: DEPI
      defaultBucket: iot-system
      tlsSkipVerify: true
    secureJsonData:
      token: fhZj6TxPeUZ5mHlLxU_MmSDrwUQtP0ZYBVWZv6_ljcffvJrAyl2WIY7aVOuTwclPx-weW-IiwrkcilHpQffr6A==
    isDefault: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
